version: 2.1
jobs:
  backend:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/squadmap/squadmap-backend
    environment:
      JVM_OPTS: -Xms512m -Xmx2g
      GRADLE_OPTS: -Xmx3g -Dorg.gradle.daemon=false -Dorg.gradle.jvmargs="-Xmx2g -XX:+HeapDumpOnOutOfMemoryError"
    steps:
      - checkout:
          path: ~/squadmap
      - restore_cache:
          keys:
            - squadmap-dependencies-{{ checksum "build.gradle" }}
            - squadmap-dependencies-
      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: squadmap-dependencies-{{ checksum "build.gradle" }}
      - run: gradle build
      - run:
          name: Analyze on SonarCloud
          command: gradle sonarqube

  frontend:
    docker:
      - image: circleci/node:10.16.0-browsers
    working_directory: ~/squadmap/squadmap-frontend
    steps:
      - checkout:
          path: ~/squadmap
      - restore_cache:
          key: squadmap-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: squadmap-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI

workflows:
  main:
    jobs:
      - backend:
          context: SonarCloud
      - frontend:
          context: SonarCloud
